### ISSUE TITLE
Stopping continuous recording and checking its status

### ISSUE THREAD

**Issue by sman-cn** [jjordanoc/azure_speech_recognition_null_safety#10]
Thank you for providing this awesome plugin!
1. How can I manually stop the continuous recording?
2. Is there a way to check if continuousRecording is currently running?

**Comment by jjordanoc** [comment]
Hello, sorry for the late reply, I've been quite busy.
1. To manually stop the continuous recording you must call `AzureSpeechRecognition.continuousRecording();` as shown in the README. This method works as a toggle between the recording and not recording states.
2. No, you must keep track of the recording state in your application's logic.
